; EnStorage — PHP runtime config
; Support upload file hingga 1GB

upload_max_filesize = 1024M
post_max_size = 1024M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

; Session
session.cookie_httponly = 1
session.use_strict_mode = 1

; OPcache
opcache.enable = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

; Realpath cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600
